[JG/DS/MP/HZ] Move dockerhub password to use ssm parameter

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -4,6 +4,7 @@ set -Eeuo pipefail
 
 DOCKER_OPS_VERSION="2.0.0"
 DOCKER_OPS_FILE="ops/docker-ops-${DOCKER_OPS_VERSION}"
+AWS_REGION="eu-west-2"
 
 mkdir -p ops
 if [[ ! -f $DOCKER_OPS_FILE ]];then
@@ -23,6 +24,16 @@ function docker_login {
   echo "$DOCKERHUB_PASSWORD" | docker login --username nhstomzo --password-stdin
 }
 
+function get_aws_ssm_secret {
+  secret_id=$1
+  secret=$(dojo "aws ssm get-parameter --with-decryption --region $AWS_REGION --name $secret_id --output text --query Parameter.Value")
+  if [ $? != 0 ]; then
+    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
+    exit 5
+  fi
+  echo $secret
+}
+
 command="$1"
 set +u
 case "${command}" in
@@ -31,6 +42,7 @@ case "${command}" in
       docker_ops::docker_build "${image_dir}" "${imagerc_filename}" "${image_name}" "${image_tag}" "${image_registry}"
       ;;
   build)
+      DOCKERHUB_PASSWORD=$(get_aws_ssm_secret "/repo/prod/user-input/gocd-dockerhub-password")
       docker_login
       ./tasks build_local
       docker_ops::push "${image_dir}" "${imagerc_filename}"
